"""@@KEY@@-templated file bodies for generated child projects.

This module provides template strings for every file a child project needs and
the substitution machinery to fill them from a :class:`~src.expand.Spec`.

Template placeholders are ``@@KEY@@``-style tokens so they remain valid Python
syntax in the surrounding source and are trivially distinguishable from
f-string or jinja patterns.

Public API
----------
apply_template(template, substitutions)
    Substitute every ``@@KEY@@`` token present in *substitutions*.
emit_file(filename, spec)
    Return the filled content for a single known filename.
emit_all(spec)
    Return a ``{relative_path: content}`` mapping for all templated files.
"""

from __future__ import annotations

import re
import textwrap

from .expand import Spec

# ---------------------------------------------------------------------------
# Placeholder pattern
# ---------------------------------------------------------------------------

_PLACEHOLDER_RE = re.compile(r"@@([A-Z0-9_]+)@@")

# ---------------------------------------------------------------------------
# Raw template strings
# ---------------------------------------------------------------------------

# Each constant is a multi-line string that may contain @@KEY@@ tokens.
# Intentional: triple-quoted strings here must NOT use f-strings — the
# placeholder tokens must survive as-is until apply_template() is called.

_TEMPLATE_ANALYSIS_PY = textwrap.dedent("""\
    \"\"\"Auto-generated analysis entry point for @@DOMAIN@@.\"\"\"
    # spec_hash: @@SPEC_HASH@@  grammar_hash: @@GRAMMAR_HASH@@
    # seed: @@SEED@@  track: @@TRACK@@  section_set: @@SECTION_SET@@
    from primitives import collect_primitives


    def run() -> None:
        \"\"\"Execute the @@DOMAIN@@ primitive suite.\"\"\"
        prims = collect_primitives()
        domain_specs = prims.get("@@DOMAIN@@", ())
        for ps in domain_specs:
            result = ps.fn(ps.example_input)
            print(f"{ps.name}: {result}")


    if __name__ == "__main__":
        run()
    """)

_TEMPLATE_TEST_ANALYSIS_PY = textwrap.dedent("""\
    \"\"\"Smoke tests for auto-generated analysis (domain: @@DOMAIN@@).\"\"\"
    # spec_hash: @@SPEC_HASH@@  grammar_hash: @@GRAMMAR_HASH@@
    # seed: @@SEED@@  track: @@TRACK@@  section_set: @@SECTION_SET@@
    from analysis import run


    def test_run_smoke() -> None:
        \"\"\"run() for domain @@DOMAIN@@ must not raise.\"\"\"
        run()  # must not raise
    """)

_TEMPLATE_PYPROJECT_TOML = textwrap.dedent("""\
    [project]
    name = "child_@@DOMAIN@@"
    version = "0.1.0"
    requires-python = ">=3.10"
    dependencies = ["numpy", "matplotlib", "pyyaml"]
    # spec_hash: @@SPEC_HASH@@  grammar_hash: @@GRAMMAR_HASH@@
    # seed: @@SEED@@  track: @@TRACK@@  section_set: @@SECTION_SET@@

    [tool.pytest.ini_options]
    pythonpath = ["."]
    testpaths = ["tests"]
    addopts = "-v --tb=short"
    """)

_TEMPLATE_ABSTRACT_MD = textwrap.dedent("""\
    ## Abstract

    Autopoietically generated project for domain `@@DOMAIN@@`.
    Spec: `@@SPEC_HASH@@`.
    Grammar: `@@GRAMMAR_HASH@@`.
    Seed: `@@SEED@@`.
    Track: @@TRACK@@.
    Section set: @@SECTION_SET@@.
    """)

_TEMPLATE_INTRODUCTION_MD = textwrap.dedent("""\
    ## Introduction

    This child project was generated by template_autopoiesis.

    - Primitive domain: @@DOMAIN@@
    - Spec hash: `@@SPEC_HASH@@`
    - Grammar hash: `@@GRAMMAR_HASH@@`
    - Seed: @@SEED@@
    - Track: @@TRACK@@
    - Section set: @@SECTION_SET@@
    """)

_TEMPLATE_RESULTS_MD = textwrap.dedent("""\
    ## Results

    Domain: **@@DOMAIN@@**

    Spec hash: `@@SPEC_HASH@@`

    ```mermaid
    flowchart LR
        A[Grammar] --> B[Spec]
        B --> C[Materialize]
        C --> D[Child: @@DOMAIN@@]
        D --> E[Tests Pass]
    ```
    """)

_TEMPLATE_LIMITATIONS_MD = textwrap.dedent("""\
    ## Limitations

    This is an autopoietically generated project.
    Results are bounded by the grammar specification.

    - Domain: @@DOMAIN@@
    - Track: @@TRACK@@
    - Section set: @@SECTION_SET@@
    """)

# ---------------------------------------------------------------------------
# Registry: filename → template string
# ---------------------------------------------------------------------------

_TEMPLATES: dict[str, str] = {
    "analysis.py": _TEMPLATE_ANALYSIS_PY,
    "tests/test_analysis.py": _TEMPLATE_TEST_ANALYSIS_PY,
    "pyproject.toml": _TEMPLATE_PYPROJECT_TOML,
    "manuscript/00_abstract.md": _TEMPLATE_ABSTRACT_MD,
    "manuscript/01_introduction.md": _TEMPLATE_INTRODUCTION_MD,
    "manuscript/03_results.md": _TEMPLATE_RESULTS_MD,
    "manuscript/06_limitations.md": _TEMPLATE_LIMITATIONS_MD,
}

# Public list of all file paths this module can emit.
TEMPLATE_PATHS: tuple[str, ...] = tuple(_TEMPLATES)

# ---------------------------------------------------------------------------
# Core substitution
# ---------------------------------------------------------------------------


def apply_template(template: str, substitutions: dict[str, str]) -> str:
    """Return *template* with every ``@@KEY@@`` token replaced by its value.

    Only keys present in *substitutions* are replaced; unknown tokens are left
    as-is so callers can stage partial substitutions.

    Parameters
    ----------
    template:
        A string that may contain ``@@KEY@@`` placeholder tokens.
    substitutions:
        Mapping of KEY → replacement value (without the ``@@`` delimiters).

    Returns
    -------
    str
        The template with all matching tokens replaced.
    """

    def _replace(m: "re.Match[str]") -> str:
        key: str = m.group(1)
        return substitutions.get(key, m.group(0))

    return _PLACEHOLDER_RE.sub(_replace, template)


# ---------------------------------------------------------------------------
# Build substitutions from a Spec
# ---------------------------------------------------------------------------


def _substitutions_from_spec(spec: Spec) -> dict[str, str]:
    """Extract all @@KEY@@ substitution values from *spec*."""
    selections = dict(spec.selections)
    return {
        "DOMAIN": spec.primitive_domain,
        "SPEC_HASH": spec.spec_hash,
        "GRAMMAR_HASH": spec.grammar_hash,
        "SEED": str(spec.seed),
        "TRACK": selections.get("track", ""),
        "SECTION_SET": selections.get("section_set", ""),
    }


# ---------------------------------------------------------------------------
# Per-file and bulk emit
# ---------------------------------------------------------------------------


def emit_file(filename: str, spec: Spec) -> str:
    """Return the filled content for *filename* using values from *spec*.

    Parameters
    ----------
    filename:
        A relative path key registered in :data:`TEMPLATE_PATHS`, e.g.
        ``"analysis.py"`` or ``"manuscript/00_abstract.md"``.
    spec:
        The expansion spec whose field values are substituted into the template.

    Returns
    -------
    str
        The fully rendered file content.

    Raises
    ------
    KeyError
        If *filename* is not a known template path.
    """
    template = _TEMPLATES[filename]
    subs = _substitutions_from_spec(spec)
    return apply_template(template, subs)


def emit_all(spec: Spec) -> dict[str, str]:
    """Emit all templated files as a ``{relative_path: content}`` mapping.

    Parameters
    ----------
    spec:
        The expansion spec to render against.

    Returns
    -------
    dict[str, str]
        Mapping from relative file path to rendered content.  Every key in
        :data:`TEMPLATE_PATHS` is present.
    """
    subs = _substitutions_from_spec(spec)
    return {path: apply_template(template, subs) for path, template in _TEMPLATES.items()}
